name: SwiftPM Jazzy Docs
description: Generates and combines jazzy docs for all products of a Swift package.
author: ser.soft GmbH
inputs:
  source:
    description: The path to the Swift package.
    required: true
    default: ${{github.workspace}}
  module-version:
    description: The version to use when generating the docs.
    required: false
  output:
    description: The path to the output folder.
    required: false
  clean:
    description: Whether a previous output should be removed before generating docs.
    required: true
    default: 'true'
  xcodebuild-destination:
    description: Tells the action to use xcodebuild (instead of `swift build`) and passes the value as `-destination` to `xcodebuild`.
    required: false
  ignore-targets:
    description: Tells the action to ignore some targets from being documented. Pass a comma delimited string of targets to ignore.
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  color: orange
  icon: book
